- name: variables preference
  hosts: localhost
  # vars: 
  #   Wishes: "Morning from play level"
  # vars_files:
  # - vars.yaml
  # vars_prompt:
  # - name: Wishes
  #   prompt: please send your wish
  #   private: no
  tasks:  
  - name: Printing variable preference
    # vars:
    #   Wishes: "Morning from task level vars"
    ansible.builtin.debug:
      msg: "Hi, Avinash Good {{Wishes}}"

# 1.Arguments
# 2.Task level
# 3.Var file
# 4.prompt
# 5.play level
# 6.inventory