- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id expense
    ignore_errors: true
    register: User_error_info

  - name: printing user error info
    ansible.builtin.debug:
      msg: "user info is : {{User_error_info}}"
  
  - name: creating user
    ansible.builtin.command: useradd expense
    when: User_error_info.rc !=0

  - name: say hello
    ansible.builtin.debug:
      msg: "Hello"
