- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg:  "Hello {{course | default('Jesus Loves You')}}"

- name: lowercase
  hosts: localhost
  tasks:
  - name: print lowercase
    ansible.builtin.debug:
      msg:  "Ansible"

- name: uppercase
  hosts:  localhost
  tasks:
  - name: print uppercase
    ansible.builtin.debug:
      msg: "Ansible uppercase"