- name: install packages with advanced
  hosts: localhost
  become: yes
  tasks:
  - name: installing packages
    ansible.builtin.dnf:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop: 
    - {name: 'mysql',stat: 'latest'}
    - {name: 'postfix',state: 'absent'}
    - {name: 'nginx',state: 'absent'}